/** Real per-post blog images downloaded from the live published site. */
type BlogImg = { src: string; alt: string; width: number; height: number };

export const blogImages: Record<string, BlogImg> = {
  "affordable-smile-makeovers-in-hamilton-cdcp-financing-cosmetic-options": { src: "/assets/images/blog/affordable-smile-makeovers-in-hamilton-cdcp-financing-cosmetic-options.png", alt: "affordable smile makeovers in hamilton cdcp financing cosmetic options — Hamilton City Dental", width: 1405, height: 799 },
  "cdcp-dentist-in-hamilton--how-hamilton-city-dental-makes-dental-care-affordable": { src: "/assets/images/blog/cdcp-dentist-in-hamilton--how-hamilton-city-dental-makes-dental-care-affordable.png", alt: "cdcp dentist in hamilton  how hamilton city dental makes dental care affordable — Hamilton City Dental", width: 625, height: 501 },
  "childrens-dentist-in-hamilton-gentle-pediatric-dental-care-at-hamilton-city-dental": { src: "/assets/images/blog/childrens-dentist-in-hamilton-gentle-pediatric-dental-care-at-hamilton-city-dental.jpg", alt: "childrens dentist in hamilton gentle pediatric dental care at hamilton city dental — Hamilton City Dental", width: 612, height: 408 },
  "dental-implants-in-hamilton-permanent-tooth-replacement-at-hamilton-city-dental": { src: "/assets/images/blog/dental-implants-in-hamilton-permanent-tooth-replacement-at-hamilton-city-dental.jpg", alt: "dental implants in hamilton permanent tooth replacement at hamilton city dental — Hamilton City Dental", width: 612, height: 408 },
  "dental-resolutions-that-actually-work-a-hamilton-dentists-guide-to-better-oral-health": { src: "/assets/images/blog/dental-resolutions-that-actually-work-a-hamilton-dentists-guide-to-better-oral-health.jpg", alt: "dental resolutions that actually work a hamilton dentists guide to better oral health — Hamilton City Dental", width: 1423, height: 931 },
  "emergency-dentist-in-hamilton-what-to-do-if-you-have-severe-tooth-pain": { src: "/assets/images/blog/emergency-dentist-in-hamilton-what-to-do-if-you-have-severe-tooth-pain.jpg", alt: "emergency dentist in hamilton what to do if you have severe tooth pain — Hamilton City Dental", width: 612, height: 408 },
  "emergency-family-dental-care-in-hamilton": { src: "/assets/images/blog/emergency-family-dental-care-in-hamilton.png", alt: "emergency family dental care in hamilton — Hamilton City Dental", width: 1075, height: 928 },
  "holiday-dental-care-in-hamilton-keep-your-smile-bright-this-christmas-hamilton-city-dental": { src: "/assets/images/blog/holiday-dental-care-in-hamilton-keep-your-smile-bright-this-christmas-hamilton-city-dental.jpg", alt: "holiday dental care in hamilton keep your smile bright this christmas hamilton city dental — Hamilton City Dental", width: 1407, height: 898 },
  "how-to-use-your-cdcp-benefits-at-hamilton-city-dental-in-2026": { src: "/assets/images/blog/how-to-use-your-cdcp-benefits-at-hamilton-city-dental-in-2026.jpg", alt: "how to use your cdcp benefits at hamilton city dental in 2026 — Hamilton City Dental", width: 612, height: 500 },
  "invisalign-near-me-in-hamilton-what-you-need-to-know-before-starting-treatment": { src: "/assets/images/blog/invisalign-near-me-in-hamilton-what-you-need-to-know-before-starting-treatment.jpg", alt: "invisalign near me in hamilton what you need to know before starting treatment — Hamilton City Dental", width: 612, height: 459 },
  "new-year-new-smile-in-hamilton-start-2026-with-better-oral-health-fresh-dental-benefits": { src: "/assets/images/blog/new-year-new-smile-in-hamilton-start-2026-with-better-oral-health-fresh-dental-benefits.jpg", alt: "new year new smile in hamilton start 2026 with better oral health fresh dental benefits — Hamilton City Dental", width: 1495, height: 924 },
  "one-visit-crowns-in-hamilton": { src: "/assets/images/blog/one-visit-crowns-in-hamilton.jpg", alt: "one visit crowns in hamilton — Hamilton City Dental", width: 612, height: 408 },
  "professional-teeth-whitening-in-hamilton-brighter-smiles-at-hamilton-city-dental": { src: "/assets/images/blog/professional-teeth-whitening-in-hamilton-brighter-smiles-at-hamilton-city-dental.jpg", alt: "professional teeth whitening in hamilton brighter smiles at hamilton city dental — Hamilton City Dental", width: 612, height: 408 },
  "root-canal-hamilton-what-to-expect-hamilton-city-dental": { src: "/assets/images/blog/root-canal-hamilton-what-to-expect-hamilton-city-dental.jpg", alt: "root canal hamilton what to expect hamilton city dental — Hamilton City Dental", width: 612, height: 371 },
  "use-your-2025-dental-benefits-before-they-expire-hamilton-city-dentals-year-end-guide": { src: "/assets/images/blog/use-your-2025-dental-benefits-before-they-expire-hamilton-city-dentals-year-end-guide.jpg", alt: "use your 2025 dental benefits before they expire hamilton city dentals year end guide — Hamilton City Dental", width: 1414, height: 859 },
  "wisdom-teeth-removal-in-hamilton-hamilton-city-dental": { src: "/assets/images/blog/wisdom-teeth-removal-in-hamilton-hamilton-city-dental.jpg", alt: "wisdom teeth removal in hamilton hamilton city dental — Hamilton City Dental", width: 612, height: 459 },
};
